feat: Add translations and fallback for form
BulbProject/bulb-project-frontend pull request #110
Opened 2020-10-05 11:47 UTC by natalia-lypovyk

2020-10-05 12:09 UTC, semenov-ol commented on public/locales/ua/calculation-result.json
> +  "no-calculation-end": " для цієї категорії "
здесь можно использовать компонент `Trans`

2020-10-05 12:09 UTC, semenov-ol commented on public/locales/ua/items.json
> +  "variant": "Більш енергоефективний варіант"
можно использовать плюрализацию

2020-10-05 12:10 UTC, drizzer14 requested changes
Переводы – не наша обязанность, поэтому прошу уделить пристальное внимание названиям ключей, чтобы в них потом никто не путался.
Сейчас ты можешь помнить, к чему относится ключ `oops`/`error`, а через неделю будешь вспоминать, где же он применяется.

Ну и, я так понял, разный подход к применению перевода вы уже обсудили и ты поправишь. Старайся в дальнейшем следить за этим, такого происходить не должно.

2020-10-05 12:10 UTC, drizzer14 commented on public/locales/en/calculation-result.json
> +}
Так были ж интерполяции?
Или что это значит?

2020-10-05 12:10 UTC, drizzer14 commented on public/locales/en/common.json
> +  "error-download": "Sorry, we were unable to load the category list.",
`Download` подразумевает скачивание чего-то куда-то, а не загрузку контента на сайте. Это скорее `categories-list-fetch-error`

2020-10-05 12:10 UTC, drizzer14 commented on public/locales/en/common.json
> +  "error": "",
Не самый конкретный ключ

2020-10-05 12:10 UTC, drizzer14 commented on public/locales/en/common.json
> +  "oops": "",
^то же самое

2020-10-05 12:10 UTC, drizzer14 commented on public/locales/en/id-modal.json
> +  "attention-id-expiration": "",
?

2020-10-05 12:10 UTC, drizzer14 commented on public/locales/ua/categories-list-component.json
> +  "no-categories": "На жаль, в систему ще не додано ні одної категорії"
Жодної

2020-10-05 12:10 UTC, drizzer14 commented on public/locales/ua/items.json
> +  "variant": "Більш енергоефективний варіант"
Не самые удачные ключи под эти фразы

2020-10-05 12:10 UTC, drizzer14 commented on public/locales/ua/specification.json
> +  "from-date": " від "
Может не будем зашивать пробелы в переводы?

2020-10-06 07:26 UTC, mrrotberry commented on src/modules/calculation-result/specification/specification.component.tsx
> +      download(result.data as string, `t('specification-for')${categoryTitle}t('from-date')${formatDateTime()}.docx`);
Нужно учесть пробелы

2020-10-06 08:54 UTC, mrrotberry approved these changes

2020-10-06 09:39 UTC, merged