fix: Fix modal closing when specification is not provided
BulbProject/bulb-project-frontend pull request #115
Opened 2020-10-08 14:54 UTC by natalia-lypovyk

2020-10-08 15:20 UTC, semenov-ol approved these changes

2020-10-16 07:33 UTC, drizzer14 requested changes

2020-10-16 07:33 UTC, drizzer14 commented on src/modules/calculation-result/specification/specification.component.tsx
> +    if (isCopying || isDownloading) {
Вот это повторялось несколько раз уже, можно объединить в одно состояние.

2020-10-16 07:33 UTC, drizzer14 commented on src/modules/calculation-result/specification/specification.component.tsx
> +      setTimeout(() => setAlertOpen(false), 5 * 1000);
Отпишись от таймаута в возврате `useEffect`

2020-10-16 07:33 UTC, drizzer14 commented on src/modules/calculation-result/specification/specification.component.tsx
> +  }, [isCopying, isResolved(result)]);
Оставляй в зависимостях просто `result`

2020-10-19 08:31 UTC, drizzer14 requested changes
Очень невнимательно написан код.
Пересмотри ещё раз все эффекты и код стайл, пожалуйста.

2020-10-19 08:31 UTC, drizzer14 commented on src/modules/calculation-result/specification/form-modal/form-modal.component.tsx
> +              }
Вот это я просил рефакторнуть и даже говорил как.
Сделай, пожалуйста.

2020-10-19 08:31 UTC, drizzer14 commented on src/modules/calculation-result/specification/form-modal/form-modal.component.tsx
> +            onChange={(value) => {
`onChange={setMode}`

2020-10-19 08:31 UTC, drizzer14 commented on src/modules/calculation-result/specification/specification.component.tsx
> +  const [identifier, setIdentifier] = useState<string>('');
Тут можно тип не указывать в дженерике

2020-10-19 08:31 UTC, drizzer14 commented on src/modules/calculation-result/specification/specification.component.tsx
> +  const isLoading = isDownloading || isCopying;
Пользуйся мемоизацией, по возможности.
Компонент тяжелый, не помешает.

2020-10-19 08:31 UTC, drizzer14 commented on src/modules/calculation-result/specification/specification.component.tsx
> +    [isCopying, isDownloading]
Этих зависимостей нет в эффекте.
А как раз то, что там есть, отсутствует в зависимостях.

2020-10-19 08:31 UTC, drizzer14 commented on src/modules/calculation-result/specification/specification.component.tsx
> +    function ddcumentDownloading() {
Опечатка.

2020-10-19 08:31 UTC, drizzer14 commented on src/modules/calculation-result/specification/specification.component.tsx
> +    [result, mode]
Пересмотри зависимости, пожалуйста. **Везде**

2020-10-19 08:31 UTC, drizzer14 commented on src/modules/calculation-result/specification/specification.component.tsx
> +        const timer = setTimeout(() => setAlertOpen(false), 2 * 1000);
Надо форматирование поправить.

2020-10-19 14:24 UTC, drizzer14 requested changes

2020-10-19 14:24 UTC, drizzer14 commented on src/modules/calculation-result/specification/form-modal/form-modal.component.tsx
> +                setDownloading(true);
`setDownloading(!isRejected)`?

2020-10-19 14:24 UTC, drizzer14 commented on src/modules/calculation-result/specification/specification.component.tsx
> +      if (isResolved(result) && mode === 'docx' && result.data instanceof Blob) {
А для чего проверка на инстанс блоба?

2020-10-19 14:24 UTC, natalia-lypovyk commented on src/modules/calculation-result/specification/specification.component.tsx
> +      if (isResolved(result) && mode === 'docx' && result.data instanceof Blob) {
для коректного завантаження документа

2020-10-21 08:23 UTC, drizzer14 approved these changes

2020-10-21 13:33 UTC, drizzer14 approved these changes

2020-10-21 13:40 UTC, mrrotberry approved these changes

2020-10-21 13:40 UTC, merged